apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fraudguard-prod
resources:
  - ../../api
  - ../../platform
  - namespace.yaml
patches:
  - path: deployment-patch.yaml
configMapGenerator:
  - name: fraudguard-api-config
    behavior: replace
    literals:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
generatorOptions:
  disableNameSuffixHash: true
