apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraudguard-api
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: fraudguard-api
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 192Mi
              ephemeral-storage: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
              ephemeral-storage: 256Mi
