apiVersion: v1
kind: Secret
metadata:
  name: fraudguard-platform-secrets
type: Opaque
stringData:
  POSTGRES_USER: airflow
  POSTGRES_PASSWORD: airflow
  POSTGRES_DB: airflow
  MLFLOW_BACKEND_STORE_URI: postgresql://mlflow:mlflow@postgres/mlflow_db
  AIRFLOW_SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
  AIRFLOW__WEBSERVER__SECRET_KEY: dev-secret-key-change-in-prod
  AIRFLOW_ADMIN_USERNAME: admin
  AIRFLOW_ADMIN_PASSWORD: admin
  AIRFLOW_ADMIN_FIRSTNAME: Admin
  AIRFLOW_ADMIN_LASTNAME: User
  AIRFLOW_ADMIN_ROLE: Admin
  AIRFLOW_ADMIN_EMAIL: admin@fraudguard.dev
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test
